# Generated by Django 5.1.1 on 2024-10-02 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('guests', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=10)),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeatAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=10)),
                ('total_seats', models.IntegerField(default=80)),
                ('remaining_seats', models.IntegerField(default=80)),
            ],
            options={
                'unique_together': {('date', 'time')},
            },
        ),
    ]
